import type { Metadata } from 'next';
import { Titillium_Web } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import PrimaryHeader from './common/header';
import './globals.css';

const titilium = Titillium_Web({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={titilium.className}>
        <PrimaryHeader />
        {children}
      </body>
    </html>
  );
}
