import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@components/Header';
import LeftNavigation from '@components/LeftNavigation';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased app-layout-body`}>
        <header className='app-header'>
          <Header />
        </header>
        <div className='app-leftnav-container'>
          <div className='app-leftnav'>
            <LeftNavigation />
          </div>
          <div className='app-root-container'>{children}</div>
        </div>
      </body>
    </html>
  );
}
